---
- id: actionlint
  name: Lint GitHub Actions workflow files
  description: Runs actionlint to lint GitHub Actions workflow files
  entry: actionlint
  language: golang
  language_version: "1.19"
  types: ["yaml"]
  files: "^.github/workflows/"
